### ISSUE TITLE
大佬 你这个 资源2好像不能播放

### ISSUE THREAD

**Issue by Yakumo-Yukari** [hezhizheng/go-movies#3]
https://film.hzz.cool/play?play_url=https%3a%2f%2fv3.dious.cc%2f20220307%2f1IoRd08b%2findex.m3u8&link=%2f%3fm%3dvod-detail-id-2007.html&episode=26  例如这个  资源2 没办法播放，资源1有时候又很慢

**Comment by hezhizheng** [comment]
这个控制不了，能否播放、播放速度都是由第三方提供的资源决定的。 @Yakumo-Yukari

**Comment by Yakumo-Yukari** [comment]
> 这个控制不了，能否播放、播放速度都是由第三方提供的资源决定的。 @Yakumo-Yukari

不可以换源吗

**Comment by Yakumo-Yukari** [comment]
> 这个控制不了，能否播放、播放速度都是由第三方提供的资源决定的。 @Yakumo-Yukari

不可以换源吗

**Comment by hezhizheng** [comment]
> > 这个控制不了，能否播放、播放速度都是由第三方提供的资源决定的。 @Yakumo-Yukari
> 
> 不可以换源吗

目前没找到其他稳定的免费源，如果有的话会加上
